### ISSUE TITLE
Method not found: 'System.String ServiceStack.StreamExtensions.ReadToEnd(System.IO.MemoryStream)

### ISSUE THREAD

**Issue by netProgrammer** [LegacyTemplates/react-spa#1]
After
```
$ npm install -g @servicestack/cli
$ dotnet-new react-spa ProjectName
```

I call `dotnet run` and result message after opening in browser:

`Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: ServiceStack.Host.Handlers.HttpAsyncTaskHandler[0]
      Failed to write error to response: {0}
System.MissingMethodException: Method not found: 'System.String ServiceStack.StreamExtensions.ReadToEnd(System.IO.MemoryStream)'.
   at ServiceStack.Serialization.JsonDataContractSerializer.SerializeToString[T](T obj)
   at ServiceStack.Formats.HtmlFormat.SerializeToStreamAsync(IRequest req, Object response, Stream outputStream)
   at ServiceStack.HttpResponseExtensionsInternal.WriteErrorToResponse(IResponse httpRes, IRequest httpReq, String contentType, String operationName, String errorMessage, Exception ex, Int32 statusCode)
   at ServiceStack.HostContext.RaiseAndHandleUncaughtException(IRequest httpReq, IResponse httpRes, String operationName, Exception ex)
   at ServiceStack.Host.Handlers.HttpAsyncTaskHandler.HandleException(IRequest httpReq, IResponse httpRes, String operationName, Exception ex)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 217.2564ms 500 text/html`

**Comment by mythz** [comment]
This is typically the result of dirty dlls, can you clear your nuget cache:

    $ nuget locals all -clear 

Then try restoring the packages again.

**Comment by netProgrammer** [comment]
Sorry my fault
